SHOW DATABASES;
USE Mail;
SHOW TABLES;

/* TABLA SERVIDOR */
CREATE TABLE SERVIDOR (
	IDSERVER INTEGER NOT NULL AUTO_INCREMENT,
	NAMESERVER VARCHAR(100) NOT NULL,
	IPSERVER VARCHAR(15),
	STATESERVER INTEGER,
	PRIMARY KEY (IDSERVER)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

/* TABLA DE CORREOS */
CREATE TABLE EMAILS (
   EMAIL VARCHAR(200) NOT NULL,
   PRIMARY KEY (EMAIL)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

/* TABLA USERS */
CREATE TABLE USERS (
	IDUSER INTEGER AUTO_INCREMENT,
	FIRSTNAME VARCHAR(200) NOT NULL,
	LASTNAME VARCHAR(200) NOT NULL,
	EMAIL    VARCHAR(200) NOT NULL,
	PASS     VARCHAR(255) NOT NULL,
	REG_DATE TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	STATE INTEGER,
	PRIMARY KEY (IDUSER),
	FOREIGN KEY (EMAIL) REFERENCES EMAILS(EMAIL)
)ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

/* TABLA CONTACT */
CREATE TABLE CONTACT (
	IDCONTACT INTEGER AUTO_INCREMENT,
	IDUSUARIOPERSONAL INTEGER,
	EMAIL VARCHAR(200) NOT NULL,
	IDSERVER INTEGER,
	PRIMARY KEY (IDCONTACT),
	FOREIGN KEY (IDUSUARIOPERSONAL) REFERENCES USERS(IDUSER),
	FOREIGN KEY (EMAIL) REFERENCES EMAILS(EMAIL),
	FOREIGN KEY (IDSERVER) REFERENCES SERVIDOR(IDSERVER)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

/*TABLA CORREO*/
CREATE TABLE CORREO (
	IDCORREO INTEGER AUTO_INCREMENT NOT NULL,
	ASUNTO VARCHAR(1000) NOT NULL,
	BODY TEXT NOT NULL,
	PARA VARCHAR(200) NOT NULL,
	DE VARCHAR(200) NOT NULL,
	SERVE INTEGER NOT NULL,
	PRIMARY KEY (IDCORREO),
	FOREIGN KEY (SERVE) REFERENCES SERVIDOR(IDSERVER),
	FOREIGN KEY (PARA) REFERENCES EMAILS(EMAIL)
)ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
/* INSERT NUEVO EMAIL */
INSERT INTO EMAILS VALUES('KEVIN@DISOURCE');

/* INSERT USER */
INSERT INTO USERS (FIRSTNAME,LASTNAME,EMAIL,PASS,STATE) 
VALUES ('KEVIN','AXPUAC', "KEVIN@DISOURCE",SHA2('KEVIN', 512),0);

/* INSERT SERVER */
INSERT INTO SERVIDOR(NAMESERVER, IPSERVER, STATESERVER)
VALUES('DISOURCE','10.0.3.211',1);